# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gigis/opal_kelly_code/chip_counter_FIFO/chip_counter_FIFO.srcs/sources_1/ip/xil_fifo_w48_d63/xil_fifo_w48_d63.xci
# IP: The module: 'xil_fifo_w48_d63' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gigis/opal_kelly_code/chip_counter_FIFO/chip_counter_FIFO.gen/sources_1/ip/xil_fifo_w48_d63/xil_fifo_w48_d63.xdc
# XDC: The top module name and the constraint reference have the same name: 'xil_fifo_w48_d63'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gigis/opal_kelly_code/chip_counter_FIFO/chip_counter_FIFO.gen/sources_1/ip/xil_fifo_w48_d63/xil_fifo_w48_d63_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'xil_fifo_w48_d63'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gigis/opal_kelly_code/chip_counter_FIFO/chip_counter_FIFO.gen/sources_1/ip/xil_fifo_w48_d63/xil_fifo_w48_d63_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xil_fifo_w48_d63'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/gigis/opal_kelly_code/chip_counter_FIFO/chip_counter_FIFO.srcs/sources_1/ip/xil_fifo_w48_d63/xil_fifo_w48_d63.xci
# IP: The module: 'xil_fifo_w48_d63' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gigis/opal_kelly_code/chip_counter_FIFO/chip_counter_FIFO.gen/sources_1/ip/xil_fifo_w48_d63/xil_fifo_w48_d63.xdc
# XDC: The top module name and the constraint reference have the same name: 'xil_fifo_w48_d63'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gigis/opal_kelly_code/chip_counter_FIFO/chip_counter_FIFO.gen/sources_1/ip/xil_fifo_w48_d63/xil_fifo_w48_d63_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'xil_fifo_w48_d63'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gigis/opal_kelly_code/chip_counter_FIFO/chip_counter_FIFO.gen/sources_1/ip/xil_fifo_w48_d63/xil_fifo_w48_d63_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xil_fifo_w48_d63'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
